add check arm-none-eabi-gcc and unify install step for linux and macos

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -45,13 +45,13 @@ addons:
     taps: RfidResearchGroup/proxmark3
 
 install:
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-    make clean;
-    make all V=1 "$MAKE_PARAMS";
-  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-    make clean;
-    make all V=1 "$MAKE_PARAMS";
+  if ! arm-none-eabi-gccx -v; then 
+    echo "arm-none-eabi-gcc [ERROR]";
+    travis_terminate 1;
   fi
+    
+  make clean;
+  make all V=1 "$MAKE_PARAMS";
 
 script:
 ## start and run a test script
